services:
  auth-service:
    environment:
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_CLIENT_AUTH: "need"
      SERVER_SSL_KEYSTORE_PATH: /app/certs/auth-keystore.p12
      SERVER_SSL_KEYSTORE_PASSWORD: ${SERVER_SSL_KEYSTORE_PASSWORD}
      SERVER_SSL_KEYSTORE_TYPE: PKCS12
      SERVER_SSL_TRUSTSTORE_PATH: /app/certs/truststore.p12
      SERVER_SSL_TRUSTSTORE_PASSWORD: ${SERVER_SSL_TRUSTSTORE_PASSWORD}

  core-banking-connector:
    environment:
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_CLIENT_AUTH: "need"
      SERVER_SSL_KEYSTORE_PATH: /app/certs/cbc-keystore.p12
      SERVER_SSL_KEYSTORE_PASSWORD: ${SERVER_SSL_KEYSTORE_PASSWORD}
      SERVER_SSL_KEYSTORE_TYPE: PKCS12
      SERVER_SSL_TRUSTSTORE_PATH: /app/certs/truststore.p12
      SERVER_SSL_TRUSTSTORE_PASSWORD: ${SERVER_SSL_TRUSTSTORE_PASSWORD}
      FINERACT_MTLS_ENABLED: "true"
      FINERACT_CLIENT_KEYSTORE_PATH: /app/certs/cbc-keystore.p12
      FINERACT_CLIENT_KEYSTORE_PASSWORD: ${SERVER_SSL_KEYSTORE_PASSWORD}
      FINERACT_TRUST_STORE_PATH: /app/certs/truststore.p12
      FINERACT_TRUST_STORE_PASSWORD: ${SERVER_SSL_TRUSTSTORE_PASSWORD}
      FINERACT_SKIP_SSL_VERIFICATION: "false"

  api-gateway:
    environment:
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_CLIENT_AUTH: "none"
      SERVER_SSL_KEYSTORE_PATH: /app/certs/gateway-keystore.p12
      SERVER_SSL_KEYSTORE_PASSWORD: ${SERVER_SSL_KEYSTORE_PASSWORD}
      SERVER_SSL_KEYSTORE_TYPE: PKCS12
      SERVER_SSL_TRUSTSTORE_PATH: /app/certs/truststore.p12
      SERVER_SSL_TRUSTSTORE_PASSWORD: ${SERVER_SSL_TRUSTSTORE_PASSWORD}
      AUTH_SERVICE_URL: https://auth-service:8082
      CBC_URL: https://core-banking-connector:8081
